version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nginx:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: nzny01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: dzny01
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
    env_file:
      - ./.envs/.env
    networks:
      - djangonetwork
  db:
    image: postgres:12-alpine
    container_name: pzny01
    env_file:
      - ./.envs/.env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork
  redis:
    image: redis:alpine
    container_name: rzny01
    expose:
      - "6379"
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge