# Generated by Django 3.2.7 on 2021-11-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text_bonus', models.TextField()),
            ],
            options={
                'verbose_name': 'Условие бонусов',
                'verbose_name_plural': 'Условия бонусов',
            },
        ),
        migrations.CreateModel(
            name='DostavkaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text_dostavka', models.TextField()),
            ],
            options={
                'verbose_name': 'Условие доставки',
                'verbose_name_plural': 'Условия доставки',
            },
        ),
    ]
