# Generated by Django 3.2.7 on 2021-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusesinfo',
            name='text_bonus',
            field=models.TextField(verbose_name='Текст бонусов'),
        ),
        migrations.AlterField(
            model_name='dostavkainfo',
            name='text_dostavka',
            field=models.TextField(verbose_name='Текст условий'),
        ),
    ]
