# Generated by Django 3.2.7 on 2021-12-07 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0020_order_reason_for_cancel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0004_stocks_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('bonus_used', models.IntegerField(verbose_name='Использованные баллы')),
                ('bonus_added', models.IntegerField(verbose_name='Начисляемые баллы')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_order', to='foods.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
