# Generated by Django 3.2.7 on 2021-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_bonustransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustransaction',
            name='bonus_added',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начисляемые баллы'),
        ),
        migrations.AlterField(
            model_name='bonustransaction',
            name='bonus_used',
            field=models.IntegerField(blank=True, null=True, verbose_name='Использованные баллы'),
        ),
    ]
