# Generated by Django 3.2.7 on 2021-12-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20211207_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonustransaction',
            name='name',
        ),
    ]
