# Generated by Django 3.2.7 on 2021-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_order_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_status_pics', verbose_name='Изображение статуса'),
        ),
    ]
