# Generated by Django 3.2.7 on 2021-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='address',
            name='entrance',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='подьезд'),
        ),
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='этаж'),
        ),
    ]
