# Generated by Django 3.2.7 on 2021-09-27 09:58

from django.db import migrations

def apply_migration(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group.objects.bulk_create([
        group(name=u'Администратор'),
        group(name=u'Оператор'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210923_0719'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]

