# Generated by Django 3.2.7 on 2021-09-27 10:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_default_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('street', models.TextField(max_length=2048, verbose_name='Улица')),
                ('apartment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Квартира')),
                ('home', models.CharField(max_length=256, verbose_name='Дом')),
                ('entrance', models.CharField(blank=True, max_length=256, null=True, verbose_name='подьезд')),
                ('floor', models.CharField(blank=True, max_length=256, null=True, verbose_name='этаж')),
            ],
        ),
    ]
