# Generated by Django 3.2.7 on 2021-09-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_alter_order_user'),
        ('accounts', '0012_websiteuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websiteuser',
            old_name='home',
            new_name='house',
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_users', to='foods.order'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
