# Generated by Django 3.2.7 on 2021-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210927_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код активации'),
        ),
    ]
