# Generated by Django 3.2.7 on 2021-09-28 10:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, default=accounts.models.uuid_generator, max_length=6, null=True, unique=True, verbose_name='Код активации'),
        ),
    ]
