# Generated by Django 3.2.7 on 2021-10-01 08:47

from django.db import migrations

def apply_migration(apps, schema_editor):
    OrderStatus = apps.get_model('foods', 'OrderStatus')
    OrderStatus.objects.bulk_create([
        OrderStatus(name=u'В обработке'),
        OrderStatus(name=u'Заказ принят'),
        OrderStatus(name=u'Заказ передан на кухню'),
        OrderStatus(name=u'Заказ передан курьеру'),
        OrderStatus(name=u'Доставлено'),
        OrderStatus(name=u'Отменено'),
    ])
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_activation_code'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
