# Generated by Django 3.2.7 on 2021-11-09 05:53

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, default=accounts.models.get_user_standart_status, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.userstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=accounts.models.uuid_generator, editable=False, max_length=6, unique=True, verbose_name='Уникальный код'),
        ),
    ]
