# Generated by Django 3.2.7 on 2021-11-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211109_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер дома'),
        ),
    ]
