# Generated by Django 3.2.7 on 2021-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_mobile_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Код уведомелния мобильного приложения'),
        ),
    ]
