# Generated by Django 3.2.7 on 2021-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_phone_number2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_admin_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Код уведомления админ панели'),
        ),
    ]
