# Generated by Django 3.2.7 on 2021-11-22 16:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_fcm_admin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_order_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма заказов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, default=accounts.models.uuid_generator, editable=False, max_length=6, null=True, unique=True, verbose_name='Уникальный код'),
        ),
    ]
