# Generated by Django 3.2.7 on 2021-11-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20211122_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fcm_mobile_token',
            new_name='fcm_token',
        ),
    ]
