# Generated by Django 3.2.7 on 2021-11-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_fcm_mobile_token_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_from_mobile',
            field=models.BooleanField(blank=True, null=True, verbose_name='Клиент мобильного приложения'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_from_web',
            field=models.BooleanField(blank=True, null=True, verbose_name='Клиент создан из чата'),
        ),
    ]
