# Generated by Django 3.2.7 on 2022-01-20 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20211130_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.userstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Уникальный код'),
        ),
    ]
