from foods.views.website.order import APIWebsiteOrderCreateView
from foods.views.website.foods import WebsiteAPIListFoodView, WebsiteAPIRetrieveFoodView
from foods.views.website.category import WebsiteAPIListFoodCategoryView