# Generated by Django 3.2.7 on 2021-09-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Статус блюд', 'verbose_name_plural': 'Статусы блюд'},
        ),
    ]
