# Generated by Django 3.2.7 on 2021-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='earn_bonus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Начисляемые баллы'),
        ),
    ]
