# Generated by Django 3.2.7 on 2021-09-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_order_earn_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='earn_bonus',
            new_name='user_bonus',
        ),
    ]
