# Generated by Django 3.2.7 on 2021-09-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_rename_earn_bonus_order_user_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категория блюд', 'verbose_name_plural': 'Категории блюд'},
        ),
    ]
