# Generated by Django 3.2.7 on 2021-09-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0009_auto_20210908_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderfoods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderfood',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderfoods', to='foods.order', verbose_name='Заказ'),
        ),
    ]
