# Generated by Django 3.2.7 on 2021-09-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_alter_orderfood_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_bonus',
        ),
        migrations.AddField(
            model_name='order',
            name='user_earn_bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начисляемые баллы'),
        ),
    ]
