# Generated by Django 3.2.7 on 2021-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_transferred_corier',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Передан на курьеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_transferred_kitchen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Передан на кухню'),
        ),
    ]
