# Generated by Django 3.2.7 on 2021-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_auto_20210930_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_accepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ принят'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_cancelled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ отменен'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заказ доставлен'),
        ),
    ]
