# Generated by Django 3.2.7 on 2021-11-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_orderfood_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Картинка'),
        ),
    ]
