# Generated by Django 3.2.7 on 2021-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason_for_cancel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина отмены'),
        ),
    ]
