# Generated by Django 3.2.7 on 2021-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0021_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
