# Generated by Django 3.2.7 on 2021-12-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0022_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('delivery', 'доставка'), ('pickup', 'самовызов'), ('inside', 'в заведении')], default='pickup', max_length=128, verbose_name='Тип'),
        ),
    ]
