# Generated by Django 3.2.7 on 2021-12-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0024_auto_20211227_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма за блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_minus_bonus',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма с вычетом бонусов'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_earn_bonus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Начисляемые баллы'),
        ),
    ]
