# Generated by Django 3.2.7 on 2021-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0026_auto_20211227_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата изменения блюда'),
        ),
    ]
