# Generated by Django 3.2.7 on 2022-01-20 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0027_food_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор создавший заказ'),
        ),
    ]
