# Generated by Django 3.2.7 on 2021-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcall',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
