# Generated by Django 3.2.7 on 2021-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0002_alter_atcall_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcall',
            name='end_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atcall',
            name='start_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
