# Generated by Django 3.2.7 on 2021-11-22 16:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0003_auto_20211122_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcall',
            name='client_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
