# Generated by Django 3.2.7 on 2021-12-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0005_auto_20211223_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcall',
            name='call_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atcall',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
