# Generated by Django 3.2.7 on 2021-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0006_auto_20211223_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcall',
            name='recording_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
