# Generated by Django 3.2.7 on 2021-12-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0007_atcall_recording_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atcall',
            old_name='dts',
            new_name='dst',
        ),
    ]
